[package]
name = "DWM-Decorator"
version = "1.0.0"
edition = "2024"
[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
[dependencies]
config = "0.15.19"
csscolorparser = { version = "0.8.3" ,features = ["default","serde"]}
serde = { version = "1.0.228" , features = ["derive"]}
thiserror = "2"
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23" ,features = ["env-filter"]}
windows = { version = "0.62.2" , features = ["Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Dwm",
    "Win32_UI_Accessibility",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_System_Threading",
    "Win32_System_Com",
]}
